### ISSUE TITLE
Land Modeling: Monoculture

### ISSUE THREAD

**Issue by BillMills** [jvamosi/Diversibee#12]
Can the effects of monoculture be captured in a feasible way?  What aspects of monoculture are most relevant here?

**Comment by jvamosi** [comment]
Monocultures do affect bee health. As much as blueberry nectar is really healthy and bees quite enjoy it, the blueberry monoculture will deprive bees of micronutrients they get from their diverse diet they usually get from foraging in the forest. Most of the bee population size would shrink due to the destruction of their habitat (they nest in the dirt and trees of the forest) but the monoculture diet would likely start to have an effect as well. I would imagine that a realistic way to model it would be to see a small positive effect of the addition of the blueberry crop to the matrix (due to the ease of foraging and extra food the bees will obtain from it) that gets eroded over time as the costs of habitat destruction starts to outweigh the benefits of additional food (i.e., bringing extra nectar back to the bee babies is only a benefit if the nest of bee babies didn't just get ploughed).
