### ISSUE TITLE
Logo example

### ISSUE THREAD

**Issue by jacobtomlinson** [jvamosi/Diversibee#40]
One of my design guys drew this up.

![bee preview](https://cloud.githubusercontent.com/assets/1610850/7988687/9e7f6f86-0adc-11e5-8c9a-19dff10ffa5a.gif)

**Comment by jvamosi** [comment]
very cute

**Comment by cgmb** [comment]
Any idea where to put it?

**Comment by jvamosi** [comment]
Beside the title perhaps?

**Comment by cgmb** [comment]
I modified the logo because the background was solid. My editing skills are limited, so instead of trying to remove the background, I just put a border around it.

Anyways. It's live on the [site](http://jvamosi.github.io/Diversibee), but here's an image (for posterity):
![diversibee](https://cloud.githubusercontent.com/assets/4886803/8100771/2f778aa6-0fcd-11e5-96f6-b754a6665885.png)
